### ISSUE TITLE
Deserialization for the format json is not supported

### ISSUE THREAD

**Issue by elyday** [webfoersterei/domain-bestellsystem-api-client#1]
Wenn ich den folgenden Code teste, schlägt mir PHP den nachfolgenden Error um die Ohren.
`$domainClient = DomainBestellsystem::createDomainClient("http://www.domain-bestellsystem.de/soapstatus/wsdl/soap.wsdl", "xx", "xxx");
$domainClient->check('ts3banner.li');`
Getestet mit PHP 7.2

> An uncaught Exception was encountered
> Type: Symfony\Component\Serializer\Exception\NotEncodableValueException
> 
> Message: Deserialization for the format json is not supported
> 
> Filename: /var/www/vhosts/wgc.li/sysbeta661.wgc.li/application/vendor/symfony/serializer/Serializer.php
> 
> Line Number: 128
> 
> Backtrace:
> 
> File: /var/www/vhosts/wgc.li/sysbeta661.wgc.li/application/vendor/webfoersterei/domain-bestellsystem-api-client/src/Client/AbstractClient.php
> Line: 65
> Function: deserialize
> 
> File: /var/www/vhosts/wgc.li/sysbeta661.wgc.li/application/vendor/webfoersterei/domain-bestellsystem-api-client/src/Client/DomainClient.php
> Line: 33
> Function: doApiCall
> 
> File: /var/www/vhosts/wgc.li/sysbeta661.wgc.li/application/controllers/Item.php
> Line: 27
> Function: check
> 
> File: /var/www/vhosts/wgc.li/sysbeta661.wgc.li/index.php
> Line: 315
> Function: require_once

**Comment by Hecke29** [comment]
Yep, thats a bug with the ClientFactory (I dont use the factory in my own projects). I'm adding a fix in a few minutes and also a minimum test to cover this.

**Comment by Hecke29** [comment]
Fixed with 0.1.0-alpha5
Thanks for reporting
