### ISSUE TITLE
pcode Error

### ISSUE THREAD

**Issue by sstratford** [webfoersterei/domain-bestellsystem-api-client#2]
Kommt bei der Abfrage eindes Handels (get)

PHP Fatal error:  Uncaught Symfony\Component\Serializer\Exception\NotNormalizableValueException: The type of the "pcode" attribute for class "Webfoersterei\DomainBestellSystemApiClient\Client\Handle\InfoResponse" must be one of "string" ("integer" given). in /home/steven/PhpstormProjects/DomBeSysApi/vendor/symfony/serializer/Normalizer/AbstractObjectNormalizer.php:357

**Comment by Hecke29** [comment]
What's the expected value of the pcode attribute?
Welchen Wert sollte die pcode Eigenschaft haben bzw. hat das remote Handle?

**Comment by sstratford** [comment]
sollte String sein wird auch so übergeben aber kommt als integer zurück

**Comment by Hecke29** [comment]
Den erwarteten WERT bitte, damit ich versuchen kann das Problem nachzustellen.

**Comment by sstratford** [comment]
63450 

das der wert den ich hinterlegt habe als pcode

**Comment by Hecke29** [comment]
Danke, schaue ich mir voraussichtlich Ende der Woche an.

**Comment by sstratford** [comment]
ok danke

**Comment by Hecke29** [comment]
Der Fix dafür (und anderes) liegt schon länger auf Halde. Ich hab jetzt eine neue Version 0.3.0-alpha1 veröffentlicht, die das enthält.

**Vorsicht**! Es gab nicht-abwärtskompatible Änderungen u.a. am DomainClient::create()

**Comment by Hecke29** [comment]
Noch als Nachtrag: Die nicht-abwärtskompatiblen Änderungen waren an den Methoden und entsprechenden Request-Objekten zu:
- DomainClient::create
- DomainClient::update
- DomainClient::transfer
- DomainClient::trade
- HandleClient::info (wurde umbenannt zu HandleClient::get)
- HandleClient::getList (wurde umbenannt zu HandleClient::list)
- HandleClient::update
- NameServerClient::rrCreate
- NameServerClient::rrDelete
- NameServerClient::zoneCreate

Alle Änderungen sind hier einsehbar: https://github.com/webfoersterei/domain-bestellsystem-api-client/compare/0.2.0-alpha1...0.3.0-alpha1
