### ISSUE TITLE
laravel 8 issue

### ISSUE THREAD

**Issue by develper1** [webfoersterei/domain-bestellsystem-api-client#3]
i want to know that this library is usable for laravel 8 or not..? because i have use the command for install this library but i got some errors.. plz tell me it is possible for laravel 8..?

**Comment by Hecke29** [comment]
Fresh `laravel/laravel (v8.5.23)`

```$# php -v
PHP 8.0.3 (cli) (built: Apr 12 2021 09:04:34) ( NTS )

$# composer require webfoersterei/domain-bestellsystem-api-client

Using version ^0.3.0@alpha for webfoersterei/domain-bestellsystem-api-client
./composer.json has been updated
Running composer update webfoersterei/domain-bestellsystem-api-client
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Root composer.json requires webfoersterei/domain-bestellsystem-api-client ^0.3.0@alpha -> satisfiable by webfoersterei/domain-bestellsystem-api-client[0.3.0-alpha1].
    - webfoersterei/domain-bestellsystem-api-client 0.3.0-alpha1 requires phpdocumentor/reflection-docblock ^4.1 -> found phpdocumentor/reflection-docblock[4.1.0, ..., 4.3.4] but the package is fixed to 5.2.2 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.
```

Laravel 8 itself is using a newer version of `phpdocumentor/reflection-docblock` than code of this repository.
I need to check the compatibility and release a new version thats compatible with `phpdocumentor/reflection-docblock^5.2`.

Thanks for reporting.
Please consider pasting the error message the next time.

**Comment by Hecke29** [comment]
Hi @develper1 ,
can you try using `composer require webfoersterei/domain-bestellsystem-api-client:dev-master`.
If it works I can release a new version.

**Comment by develper1** [comment]
@Hecke29 thanks for replying against my issue .. i have successfully install this package in my laravel 8 project . but i face some issues .. i want to get domains.. and i face an error 'invalid value for level'. i can not know that what is correct value for level parameter

**Comment by Hecke29** [comment]
Resolved.
Level question moved to #5
