### ISSUE TITLE
Invalid Value for Level

### ISSUE THREAD

**Issue by Hecke29** [webfoersterei/domain-bestellsystem-api-client#5]
i face some issues .. i want to get domains.. and i face an error 'invalid value for level'. i can not know that what is correct value for level parameter

_Originally posted by @develper1 in https://github.com/webfoersterei/domain-bestellsystem-api-client/issues/3#issuecomment-895194870_

**Comment by develper1** [comment]
@Hecke29  what is the right value for level parameter ..? please tell me

**Comment by Hecke29** [comment]
Hi,

what value do you use for level?
The default value is `all`. See:
https://github.com/webfoersterei/domain-bestellsystem-api-client/blob/790bfd3295496f5edfd1cd6b4126d0c994500e48/src/Client/DomainClient.php#L92

This project is just the client providing some typed Response-Objects and Clients to call the API in a safe manner. For valid values and how to operate the API you need to look into the official API-documentation.
In this case `own` or `reselleronly` are the other valid options.

**Comment by develper1** [comment]
> Hi,
> 
> what value do you use for level?
> The default value is `all`. See:
> https://github.com/webfoersterei/domain-bestellsystem-api-client/blob/790bfd3295496f5edfd1cd6b4126d0c994500e48/src/Client/DomainClient.php#L92
> 
> This project is just the client providing some typed Response-Objects and Clients to call the API in a safe manner. For valid values and how to operate the API you need to look into the official API-documentation.
> In this case `own` or `reselleronly` are the other valid options.

please give me the link of official API-documentation if you don't mind .. because i also try for giving 'own' and 'reselleronly' and i face same error
![50](https://user-images.githubusercontent.com/76731493/128710236-4c7fdaf4-5104-4675-b6d6-faeaaf9eb69c.PNG)

**Comment by develper1** [comment]
you check that..
![51](https://user-images.githubusercontent.com/76731493/128710486-d447b0f0-fce7-415d-8012-bfd917dbecaa.PNG)

**Comment by Hecke29** [comment]
Hi,

the link I know is https://www.domain-bestellsystem.de/soapstatus/doc/SOAP-Dokumentation_whitelabeled.pdf (it's in german).

If you want further help **I need to see what you are trying to send / a verifyable minimal example** of how you call the methods.
Your screenshot does not even show with URL your are sending to neither the contents of your request.

I can tell that the following code works:
```php
$domainClient = \Webfoersterei\DomainBestellSystemApiClient\ClientFactory::createDomainClient(API_URL, API_USERNAME, API_PASSWORD);
var_dump($domainClient->list());
```

with result
```
object(Webfoersterei\DomainBestellSystemApiClient\Client\Domain\ListResponse)#89 (6) {
  ["domainsList":"Webfoersterei\DomainBestellSystemApiClient\Client\Domain\ListResponse":private]=>
  array(2) {
    [0]=>
    object(Webfoersterei\DomainBestellSystemApiClient\Client\Domain\ListResponseItem)#111 (3) {
      ["domainName":"Webfoersterei\DomainBestellSystemApiClient\Client\Domain\ListResponseItem":private]=>
      string(0)"example.de"
      ["tld":"Webfoersterei\DomainBestellSystemApiClient\Client\Domain\ListResponseItem":private]=>
      string(2) "de"
      ["reseller":"Webfoersterei\DomainBestellSystemApiClient\Client\Domain\ListResponseItem":private]=>
      string(0) "API_USERNAME"
    }
...
```

**Comment by develper1** [comment]
@Hecke29 thank you soo much . now i have get response successfully.. first i can call by  $domainClient->list($offset); this method and i face error.. now i can call by this method and i get response.
![52](https://user-images.githubusercontent.com/76731493/128711721-247089e9-4752-47cf-b4db-73d56fa9c77e.PNG)

**Comment by Hecke29** [comment]
I think since PHP8 you can do something like this with named parameters:
`$domainClient->list(offset: $offset);`
otherwise to provide an offset, remember to keep all arguments in order:
`$domainClient->list('all', null, $offset);`

**Comment by develper1** [comment]
@Hecke29 i have 1 last question please .. it is possible to get owner field in Info by domain name ..?

**Comment by develper1** [comment]
i want to get this owner field .. 
![53](https://user-images.githubusercontent.com/76731493/128712584-4b77a3e5-7815-4d37-a85f-5200ec5810e2.PNG)

**Comment by Hecke29** [comment]
> @Hecke29 i have 1 last question please .. it is possible to get owner field in Info by domain name ..?

If I remember correctly you have to first get the Domain Info for a specific Domain via `$domainClient->info($domain)` and then look into the `ownerC` property which is a handle string. Then query that handle via `$handleClient->info($ownerC)`. That returns a `InfoResponse` which has `firstname`, `lastname` and `company`-property.

Thats unpleasant but that's how the API is built, this client-library does not change that.
