### ISSUE TITLE
Create domain issue

### ISSUE THREAD

**Issue by develper1** [webfoersterei/domain-bestellsystem-api-client#7]
I want to create domain but i face some issue like .. pass second argument .. please help me and tell me that how i pass second argument for create domain.. I am passing second argument like this but i face an error..
![58](https://user-images.githubusercontent.com/76731493/129015014-09723203-2015-49bc-b2db-b30d8a5e8bdf.PNG)

**Comment by Hecke29** [comment]
Please provide the error message / stack

**Comment by develper1** [comment]
> Please provide the error message / stack
i face this error
![59](https://user-images.githubusercontent.com/76731493/129015712-c8820855-471e-4a28-953b-8caee4216f2d.PNG)

**Comment by Hecke29** [comment]
It says what the error is: You have to create a CreateRequest-object to provide as second parameter, not an array. If you would use an IDE that's not VisualStudioCode (but e.g. PHPStorm) it would also highlight it as invalid red.
Maybe this is not a good project to learn programming PHP
